apiVersion: v1
kind: Service
metadata:
  name: open5glos-control
  namespace: free5gc
  labels:
    app: free5gc
    nf: open5glos
    component: admission-control
spec:
  type: ClusterIP
  selector:
    app: free5gc
    nf: open5glos
    io.service: open5glos
  ports:
  - name: admission-api
    protocol: TCP
    port: 9091
    targetPort: admission-api
