apiVersion: v1
kind: Service
metadata:
  name: 5glos-gateway
  namespace: free5gc
  labels:
    app: free5gc
    nf: 5glos-gateway
    io.service: 5glos-gateway
spec:
  type: NodePort
  ports:
  - port: 38412
    targetPort: 38412
    nodePort: 30412
    protocol: SCTP
    name: ngap
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: free5gc
    nf: 5glos-gateway
    io.service: 5glos-gateway