apiVersion: v1
kind: Pod
metadata:
  name: sctp-server
  labels:
    app: sctp-server
spec:
  containers:
    - name: server
      image: alpine
      command:
        [
          "sh",
          "-c",
          "apk add socat && socat -v -d -d SCTP-LISTEN:38412,reuseaddr,fork STDOUT",
        ]
      ports:
        - containerPort: 38412
          protocol: SCTP
---
apiVersion: v1
kind: Service
metadata:
  name: sctp-server-svc
spec:
  selector:
    app: sctp-server
  ports:
    - name: sctp
      port: 38412
      targetPort: 38412
      protocol: SCTP
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-client
spec:
  containers:
    - name: client
      image: alpine
      command:
        [
          "sh",
          "-c",
          "apk add socat && echo 'Hello SCTP' | socat -v -d -d STDIN SCTP:sctp-server-svc:38412",
        ]
